AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role with custom inline policy and trust policy

Resources:
  CustomIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyCustomIAMRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com  # <-- Customize this as needed
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: "123456789012"  # Optional condition
      Path: /
      Policies:
        - PolicyName: CustomInlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::my-bucket
                  - arn:aws:s3:::my-bucket/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                Resource: "*"
